//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fitnesspro.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminPackageName
    {
        public int PackageId { get; set; }
        public string PackageName { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> Months { get; set; }
    }
}
