//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fitnesspro.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntityPayment
    {
        public int RecieptNumber { get; set; }
        public string PaymentType { get; set; }
        public Nullable<decimal> PaymentAmount { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<long> ReferrenceNumber { get; set; }
        public Nullable<int> PackageId { get; set; }
    
        public virtual PackageDetail PackageDetail { get; set; }
    }
}
