//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fitnesspro.Repository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FitnessProEntities : DbContext
    {
        public FitnessProEntities()
            : base("name=FitnessProEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminPackageName> AdminPackageNames { get; set; }
        public virtual DbSet<ClosedDate> ClosedDates { get; set; }
        public virtual DbSet<Duration> Durations { get; set; }
        public virtual DbSet<EntityPayment> EntityPayments { get; set; }
        public virtual DbSet<EntityType> EntityTypes { get; set; }
        public virtual DbSet<ExtraTime> ExtraTimes { get; set; }
        public virtual DbSet<FitnessList> FitnessLists { get; set; }
        public virtual DbSet<OnlineBookingService> OnlineBookingServices { get; set; }
        public virtual DbSet<PackageDetail> PackageDetails { get; set; }
        public virtual DbSet<Repeat> Repeats { get; set; }
        public virtual DbSet<Service> Services { get; set; }
        public virtual DbSet<ServiceAvailable> ServiceAvailables { get; set; }
        public virtual DbSet<ServiceGroup> ServiceGroups { get; set; }
        public virtual DbSet<ServicePriceOption> ServicePriceOptions { get; set; }
        public virtual DbSet<ServiceSetting> ServiceSettings { get; set; }
        public virtual DbSet<ShiftTiming> ShiftTimings { get; set; }
        public virtual DbSet<Staff> Staffs { get; set; }
        public virtual DbSet<StaffWorkingHour> StaffWorkingHours { get; set; }
        public virtual DbSet<Tax> Taxes { get; set; }
        public virtual DbSet<UserPermission> UserPermissions { get; set; }
        public virtual DbSet<VoucherExpiry> VoucherExpiries { get; set; }
    }
}
