//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fitnesspro.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServicePriceOption
    {
        public int PricingId { get; set; }
        public Nullable<int> DurationId { get; set; }
        public Nullable<decimal> RetailPrice { get; set; }
        public string PricingName { get; set; }
        public Nullable<decimal> SpecialPrice { get; set; }
        public Nullable<int> ServiceId { get; set; }
    
        public virtual Service Service { get; set; }
    }
}
