//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fitnesspro.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffWorkingHour
    {
        public int WorkingHourId { get; set; }
        public Nullable<System.TimeSpan> ShiftStart { get; set; }
        public Nullable<System.TimeSpan> ShiftEnd { get; set; }
        public Nullable<int> Repeat { get; set; }
        public Nullable<int> StaffId { get; set; }
    
        public virtual Staff Staff { get; set; }
    }
}
